[workspace]
resolver = "2"

members = [
    "ch3-conditions",
    "ch3-constants",
    "ch3-datatypes",
    "ch3-for",
    "ch3-functions",
    "ch3-loop-1",
    "ch3-shadowing",
    "ch3-while",
    "ch4-4-1",
]