[package]
name = "ch10_10_14_trait_default_impl_new_methods"
version = "0.1.0"
edition = "2021"

[dependencies]

[lib]
name = "ch10_10_14_trait_default_impl_new_methods"
path = "src/lib.rs"

[[bin]]
name = "ch10_10_14_trait_default_impl_new_methods_bin"
path = "src/main.rs"