[package]
name = "ch10-10-14-trait-as-parameters"
version = "0.1.0"
edition = "2021"

[dependencies]

[lib]
name = "ch10_10_14_trait_as_parameters"
path = "src/lib.rs"

[[bin]]
name = "ch10_10_14_trait_as_parameters"
path = "src/main.rs"