[workspace]
name = "inpyjama-30-days-of-rust"
version = "0.1.0"
edition = "2021"

members = [
    "day2/hello",
    "day3",
    "day4",
    "day5",
    "day6",
    "day7",
    "day8",
    "day9",
    "day10",
]